/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Netdx.ConversationTracker
{
  public enum FlowOrientation
  {
    Undefined = 0,
    Upflow = 1,
    Downflow = 2,
  }
}
