/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Netdx.ConversationTracker
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class PcapPseudoheader : TBase
  {
    private long _FileOffset;
    private int _LinkType;
    private byte[] _Filter;

    public long FileOffset
    {
      get
      {
        return _FileOffset;
      }
      set
      {
        __isset.FileOffset = true;
        this._FileOffset = value;
      }
    }

    public int LinkType
    {
      get
      {
        return _LinkType;
      }
      set
      {
        __isset.LinkType = true;
        this._LinkType = value;
      }
    }

    public byte[] Filter
    {
      get
      {
        return _Filter;
      }
      set
      {
        __isset.Filter = true;
        this._Filter = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool FileOffset;
      public bool LinkType;
      public bool Filter;
    }

    public PcapPseudoheader() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I64) {
                FileOffset = iprot.ReadI64();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.I32) {
                LinkType = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.String) {
                Filter = iprot.ReadBinary();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("PcapPseudoheader");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.FileOffset) {
          field.Name = "FileOffset";
          field.Type = TType.I64;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteI64(FileOffset);
          oprot.WriteFieldEnd();
        }
        if (__isset.LinkType) {
          field.Name = "LinkType";
          field.Type = TType.I32;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(LinkType);
          oprot.WriteFieldEnd();
        }
        if (Filter != null && __isset.Filter) {
          field.Name = "Filter";
          field.Type = TType.String;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteBinary(Filter);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("PcapPseudoheader(");
      bool __first = true;
      if (__isset.FileOffset) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("FileOffset: ");
        __sb.Append(FileOffset);
      }
      if (__isset.LinkType) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("LinkType: ");
        __sb.Append(LinkType);
      }
      if (Filter != null && __isset.Filter) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Filter: ");
        __sb.Append(Filter);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
