/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Netdx.ConversationTracker
{
  public enum ProtocolType
  {
    IP = 0,
    ICMP = 1,
    IGMP = 2,
    IPIP = 4,
    TCP = 6,
    EGP = 8,
    PUP = 12,
    UDP = 17,
    IDP = 22,
    TP = 29,
    IPv6 = 41,
    ROUTING = 43,
    FRAGMENT = 44,
    RSVP = 46,
    GRE = 47,
    ESP = 50,
    AH = 51,
    ICMPV6 = 58,
    NONE = 59,
    DSTOPTS = 60,
    MTP = 92,
    ENCAP = 98,
    PIM = 103,
    COMP = 108,
    RAW = 255,
  }
}
