/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Netdx.ConversationTracker
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class TcpFlowFeaturesRecord : TBase
  {
    private int _PushTcp;
    private int _InitWindowsBytes;
    private int _RttSamples;
    private List<PacketMetrics> _Packets;

    public int PushTcp
    {
      get
      {
        return _PushTcp;
      }
      set
      {
        __isset.PushTcp = true;
        this._PushTcp = value;
      }
    }

    public int InitWindowsBytes
    {
      get
      {
        return _InitWindowsBytes;
      }
      set
      {
        __isset.InitWindowsBytes = true;
        this._InitWindowsBytes = value;
      }
    }

    public int RttSamples
    {
      get
      {
        return _RttSamples;
      }
      set
      {
        __isset.RttSamples = true;
        this._RttSamples = value;
      }
    }

    public List<PacketMetrics> Packets
    {
      get
      {
        return _Packets;
      }
      set
      {
        __isset.Packets = true;
        this._Packets = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool PushTcp;
      public bool InitWindowsBytes;
      public bool RttSamples;
      public bool Packets;
    }

    public TcpFlowFeaturesRecord() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32) {
                PushTcp = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.I32) {
                InitWindowsBytes = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.I32) {
                RttSamples = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.List) {
                {
                  Packets = new List<PacketMetrics>();
                  TList _list0 = iprot.ReadListBegin();
                  for( int _i1 = 0; _i1 < _list0.Count; ++_i1)
                  {
                    PacketMetrics _elem2;
                    _elem2 = new PacketMetrics();
                    _elem2.Read(iprot);
                    Packets.Add(_elem2);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("TcpFlowFeaturesRecord");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.PushTcp) {
          field.Name = "PushTcp";
          field.Type = TType.I32;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(PushTcp);
          oprot.WriteFieldEnd();
        }
        if (__isset.InitWindowsBytes) {
          field.Name = "InitWindowsBytes";
          field.Type = TType.I32;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(InitWindowsBytes);
          oprot.WriteFieldEnd();
        }
        if (__isset.RttSamples) {
          field.Name = "RttSamples";
          field.Type = TType.I32;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(RttSamples);
          oprot.WriteFieldEnd();
        }
        if (Packets != null && __isset.Packets) {
          field.Name = "Packets";
          field.Type = TType.List;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.Struct, Packets.Count));
            foreach (PacketMetrics _iter3 in Packets)
            {
              _iter3.Write(oprot);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("TcpFlowFeaturesRecord(");
      bool __first = true;
      if (__isset.PushTcp) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("PushTcp: ");
        __sb.Append(PushTcp);
      }
      if (__isset.InitWindowsBytes) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("InitWindowsBytes: ");
        __sb.Append(InitWindowsBytes);
      }
      if (__isset.RttSamples) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("RttSamples: ");
        __sb.Append(RttSamples);
      }
      if (Packets != null && __isset.Packets) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Packets: ");
        __sb.Append(Packets);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
